version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      # cache node modules for faster builds
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      # note: had to change to --single-run to --watch=false and --browser to --browsers=ChromeHeadless
      - run: npm run test -- --watch=false --no-progress --browsers=ChromeHeadless
      # note: had to remove obsolete --no-progress, and change config ref to protractorConfig
      - run: npm run e2e -- --protractorConfig=e2e/protractor-ci.conf.js

